export const DESTINATIONS = {
    'ANU': 'Antigua and Barbuda',
    'NAS': 'Bahamas',
    'BZE': 'Belize',
    'LIR': 'Costa Rica',
    'SJO': 'San José',
    'PUJ': 'Punta Cana, DR',
    'SDQ': 'Santo Domingo, DR',
    'SAL': 'El Salvador',
    'GUA': 'Guatemala',
    'KIN': 'Jamaica',
    'MBJ': 'St. James',
    'SJD': 'Los Cabos, MX',
    'GDL': 'Guadalajara, MX',
    'PVR': 'Puerto Vallarta, MX',
    'MTY': 'Monetrrey, MX',
    'CUN': 'Cancun, MX',
    'CZM': 'Cozumel, MX',
    'SXM': 'St. Maarten',
    'PHX': 'Phoenix',
    'XNA': 'Arkansas',
    'LIT': 'Little Rock, AR',
    'OAK': 'Oakland',
    'ONT': 'Ontario',
    'SNA': 'Orange County',
    'SMF': 'Sacramento',
    'SAN': 'San Diego',
    'SFO': 'San Francisco',
    'DEN': 'Colorado',
    'BDL': 'Connecticut',
    'FLL': 'Fort Lauderdale, FL',
    'RSW': 'Fort Myers, FL',
    'JAX': 'Jacksonville, FL',
    'MIA': 'Miami, FL',
    'MCO': 'Orlando, FL',
    'PNS': 'Pensacola, FL',
    'SRQ': 'Sarasota, FL',
    'TPA': 'Tampa, FL',
    'PBI': 'West Palm Beach, FL',
    'ATL': 'Atlanta, Georgia',
    'SAV': 'Savannah, Georgia',
    'BMI': 'Illinois',
    'MDW': 'Chicago',
    'IND': 'Indiana',
    'CID': 'Cedar rapids, Iowa',
    'DSM': 'Des Moines, Iowa',
    'CVG': 'Kentucky',
    'MSY': 'Louisiana',
    'PWM': 'Maine',
    'BWI': 'Maryland',
    'BOS': 'Massachusetts',
    'DTW': 'Michigan',
    'GRR': 'Grand Rapids, MI',
    'MSP': 'Minnesota',
    'MCI': 'Missouri',
    'STL': 'St. Louis',
    'MSO': 'Montana',
    'OMA': 'Nebraska',
    'LAS': 'Las Vegas',
    'TTN': 'New Jersey',
    'BUF': 'New York',
    'ISP': 'Long Island/Islip',
    'SWF': 'Newburgh',
    'LGA': 'New York City',
    'SYR': 'Syracuse',
    'CLT': 'North Carolina',
    'RDU': 'Raleigh, NC',
    'FAR': 'North Dakota',
    'CLE': 'Ohio',
    'CMH': 'Columbus',
    'OKC': 'Oklahoma',
    'PDX': 'Oregon',
    'MDT': 'Pennsylvania',
    'PHL': 'Philadelphia',
    'PIT': 'Pittsburgh',
    'BQN': 'Aguadilla, Puerto Rico',
    'PSE': 'Ponce, Puerto Rico',
    'SJU': 'San Juan, Puerto Rico',
    'CHS': 'Charleston, South Carolina',
    'MYR': 'Myrtle Beach, SC',
    'TYS': 'Tennessee',
    'MEM': 'Memphis',
    'BNA': 'Nashville',
    'AUS': 'Austin, Texas',
    'DFW': 'Dallas/Fort Worth',
    'ELP': 'El Paso',
    'IAH': 'Houston',
    'SAT': 'San Antonio',
    'STT': 'U.S. Virgin Islands',
    'SLC': 'Utah',
    'DCA': 'Virginia',
    'ORF': 'Norfolk',
    'SEA': 'Washington',
    'GRB': 'Wisconsin',
    'MSN': 'Madison',
    'MKE': 'Milwaukee'
}
